/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.73
</auto-generated>
------------------------------------------------------------------------------ */

using Newtonsoft.Json;
using SitefinityWebApp.Configuration;
using SitefinityWebApp.Mvc.ViewModels;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Telerik.Sitefinity.Configuration;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class FeaturedArticleCarouselModel
	{
		private readonly FeaturedNewsConfig config;
        public FeaturedArticleCarouselModel() => config = Config.Get<FeaturedNewsConfig>();

        public List<FeaturedNewsModel> GetViewModel() => Task.Run(() => this.GetLaunchAsync()).Result;
        /// <summary>
        /// Realiza la llamada al API y obtiene los datos.
        /// </summary>
        /// <returns></returns>
        private async Task<List<FeaturedNewsModel>> GetLaunchAsync()
        {
            if (config.IsActive)
            {
                string jsonString = "http://localhost:1969/api/featured-articles/newsitems/featured-article-and-image"; //default 

                using (var client = new HttpClient())
                {
                    var response = await client.GetAsync(config.Endpoint);
                    if (response != null)
                    {
                        response.EnsureSuccessStatusCode();
                        jsonString = await response.Content.ReadAsStringAsync();
                        
                    }
                    try
                    {
                        var wrapper = JsonConvert.DeserializeObject<FeaturedNewsResponse>(jsonString);
                        return wrapper?.Value; 
                    }
                    catch { return null; }
                }
            }
            else return null;
        }
    }
}