/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.73
</auto-generated>
------------------------------------------------------------------------------ */

using Resources;
using SitefinityWebApp.App_GlobalResources;
using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Services;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "FeaturedArticleCarousel_MVC", Title = "Featured Article Carousel", SectionName = "CustomWidgets")]
	public class FeaturedArticleCarouselController : Controller, IPersonalizable
	{

		public ActionResult Index()
		{
            ViewBag.DisabledModule=FeaturedNewsCarouselResources.DisabledModule;
			var model = new FeaturedArticleCarouselModel();
            var viewModel = model.GetViewModel();
            if (viewModel != null)
            {
                //var threadCulture = System.Threading.Thread.CurrentThread.CurrentUICulture;
                // var sitefinityCulture = SystemManager.CurrentContext.Culture;
                ViewBag.Title=FeaturedNewsCarouselResources.Title;
                ViewBag.ReadMore = FeaturedNewsCarouselResources.ReadMore;
                ViewBag.Previous=FeaturedNewsCarouselResources.Previous;
                ViewBag.Next=FeaturedNewsCarouselResources.Next;
            }
            return View(viewModel);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}