/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.73
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.App_GlobalResources;
using SitefinityWebApp.Mvc.Models;
using System.Threading;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Services;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "FlightData_MVC", Title = "SpaceX Latest Flight", SectionName = "Custom Widgets")]
	public class FlightDataController : Controller, IPersonalizable
	{
        /// <summary>
        /// Obtiene la data de GetViewModel() y la renderiza en el widget.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
		{
            var model = new FlightDataModel();
            var viewModel = model.GetViewModel();
            ViewBag.Title = FlightDataResources.Title;
            ViewBag.DisabledModule = FlightDataResources.DisabledModule;

            if (viewModel != null) { 
            
            ViewBag.FlightNumberLabel= FlightDataResources.FlightNumberLabel;
            ViewBag.MissionStatusLabel = FlightDataResources.MissionStatusLabel;

            
            if (viewModel.Success)
            {
                ViewBag.StatusMessage = FlightDataResources.SuccessMessage;
            }
            else 
            {
                ViewBag.StatusMessage = FlightDataResources.FailureMessage;
            }}
            return View("Index",viewModel);
            
        }
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}