using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using AngleSharp.Dom;
using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.RestSdk;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.AspNetCore.Widgets.Models.Common;
using Progress.Sitefinity.AspNetCore.Widgets.ViewComponents.Common;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using Progress.Sitefinity.Renderer.Models;
using Progress.Sitefinity.RestSdk;
using Progress.Sitefinity.RestSdk.Client;
using Progress.Sitefinity.RestSdk.Dto;
using Progress.Sitefinity.RestSdk.OData;
using WebApp.ViewModels.Card;

namespace ViewComponents.Card
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget(Title = "Custom Card Widget", Category = WidgetCategory.Content)]
    public class CardViewComponent : ViewComponent
    {
        //los clientes permiten realizar operaciones CRUD
        private IRestClient _restClient; //CRUD general
        private IODataRestClient _odataClient; //Bound o Unbound
        private IStyleClassesProvider _styleClasses;
        public CardViewComponent(IRestClient client, IStyleClassesProvider styleClasses, IODataRestClient odataClient) {
            _restClient = client;
            _styleClasses = styleClasses;
            _odataClient = odataClient;
        
        }
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(IViewComponentContext<CardEntity> context)
        {
            CardViewModel model = new CardViewModel();

            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            await GetImageAsync(context, model);

            BuildSectionMargins(context, model);

            //build model
            model.ButtonStyle = context.Entity.ButtonStyle.ToString().ToLower();
            model.CardTitle = context.Entity.CardTitle;
            model.Link = context.Entity.Link.Href;
            return View(context.Entity.ViewName, model);
        }

        private void BuildSectionMargins(IViewComponentContext<CardEntity> context, CardViewModel model)
        {
            var margins = _styleClasses.GetMarginsClasses(context.Entity.Margins);
            if (!string.IsNullOrEmpty(margins))
            {
                model.Margins = margins;
            }
        }

        private async Task GetImageAsync(IViewComponentContext<CardEntity> context, CardViewModel model)
        {
            if (context.Entity.Image.HasSelectedItems())
            {
                var imgResult = await _restClient.GetItems<ImageDto>(context.Entity.Image);
                if (imgResult.Items.Count > 0)
                {
                    model.Image=imgResult.Items[0];
                }
            }
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class CardEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        [ContentSection(cardSectionName)]
        [Content(Type=KnownContentTypes.Images, AllowMultipleItemsSelection =false)]
        [Required]
        public MixedContentContext Image { get; set; }

        [ContentSection(cardSectionName)]
        [DisplayName("Card Title")]
        [Required]
        public string CardTitle { get; set; }

        [ContentSection(buttonSectionName)]
        [DisplayName("Button Style")]
        [DefaultValue("primary")]
        public BootstrapColor ButtonStyle { get; set; }

        [ContentSection(cardSectionName)]
        [DisplayName("Margins")]
        [TableView("Section")]
        public MarginStyle Margins { get; set; }
        
        [ContentSection(buttonSectionName)]
        [Description("Additional URL")]
        public LinkModel Link { get; set; }

        [ContentSection(cardSectionName)]
        [DisplayName("Template")]
        [ViewSelector]
        [DefaultValue("Default")]
        public string ViewName { get; set; }

        private const string cardSectionName = "Card";
        private const string buttonSectionName = "Button";
    }

    public enum BootstrapColor
    {
        Primary,
        Secondary,
        Success,
        Info,
        Light,
        Dark,
        Link,
        Warning,
        Danger
    }
}
